<%@ Page Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="TestDevPricingMangement.aspx.cs" MaintainScrollPositionOnPostback="true" Inherits="TestDevPricingMangement" Title="Test Pricing Mangement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">

    <script type="text/javascript">
        // It is important to place this JavaScript code after ScriptManager1
        var xPos, yPos;
        var prm = Sys.WebForms.PageRequestManager.getInstance();

        function BeginRequestHandler(sender, args) {
            if ($get('<%=treePanel.ClientID%>') != null) {
                // Get X and Y positions of scrollbar before the partial postback
                xPos = $get('<%=treePanel.ClientID%>').scrollLeft;
                yPos = $get('<%=treePanel.ClientID%>').scrollTop;
            }
        }

        function EndRequestHandler(sender, args) {
            if ($get('<%=treePanel.ClientID%>') != null) {
                // Set X and Y positions back to the scrollbar
                // after partial postback
                $get('<%=treePanel.ClientID%>').scrollLeft = xPos;
                $get('<%=treePanel.ClientID%>').scrollTop = yPos;
            }
        }

        prm.add_beginRequest(BeginRequestHandler);
        prm.add_endRequest(EndRequestHandler);
    </script>
    <%--<table>
        <tr>
            <td>
                <asp:FileUpload ID="ExcelUploader" runat="server"></asp:FileUpload>
                <asp:Button ID="btnUpload" runat="server" CssClass="button" Text="Load" OnClick="btnUpload_Click" />
            </td>
        </tr>
    </table>--%>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <table cellpadding="0" cellspacing="2" width="100%">
                <tr>
                    <td align="center" class="cssHeader">
                        <table cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td align="left"><span class="titleNu">Pricing Management</span></td>
                                <td align="right"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <table style="width: 100%;">
                            <tr>
                                <td width="300" valign="top">
                                    <table cellpadding="0" cellspacing="2">
                                        <tr>
                                            <td align="left" colspan="2" valign="top" style="width: 500px; height: 16px;">
                                                <asp:Button ID="btnHome" runat="server" CssClass="homeButton" OnClick="btnHome_Click"
                                                    Text="HOME" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="top">
                                                <asp:Panel runat="Server" ID="treePanel" Style="overflow: auto">
                                                    <asp:TreeView ID="trvSection" runat="server" OnSelectedNodeChanged="trvSection_SelectedNodeChanged"
                                                        ImageSet="Arrows" Height="600px" Width="150px" AutoGenerateDataBindings="False"
                                                        ExpandDepth="0" OnTreeNodeExpanded="trvSection_TreeNodeExpanded" SelectAction="Expand">
                                                        <ParentNodeStyle Font-Bold="False" />
                                                        <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
                                                        <SelectedNodeStyle Font-Underline="True" ForeColor="#5555DD" HorizontalPadding="0px"
                                                            VerticalPadding="0px" />
                                                        <NodeStyle Font-Names="Tahoma" Font-Size="10pt" ForeColor="Black" HorizontalPadding="5px"
                                                            NodeSpacing="0px" VerticalPadding="0px" />
                                                    </asp:TreeView>
                                                </asp:Panel>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td align="center" valign="top">
                                    <table style="width: 100%;">
                                        <tr>
                                            <td align="center" colspan="2" valign="top">
                                                <table width="100%" class="subHeader01">
                                                    <tr>
                                                        <td>
                                                            <asp:Label ID="lblMainSection" runat="server" Text="Main Section"></asp:Label>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2" style="width: 500px; height: 16px;" valign="top">
                                                <table width="100%">
                                                    <tr>
                                                        <td align="center">
                                                            <asp:Label ID="lblMainSecResult" runat="server" Text=""></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="right">&nbsp;&nbsp;
                                                            <asp:Button ID="btnAddnewRow" runat="server" CssClass="button" OnClick="btnAddnewRow_Click" Text="Add New Section" Visible="False" />
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <asp:GridView ID="grdMainSection" runat="server" AutoGenerateColumns="False" CssClass="mGrid"
                                                                OnRowCommand="grdMainSection_RowCommand" OnRowDataBound="grdMainSection_RowDataBound"
                                                                OnRowEditing="grdMainSection_RowEditing" OnRowUpdating="grdMainSection_RowUpdating"
                                                                PageSize="200" TabIndex="2" Width="100%" AllowSorting="True" OnSorting="grdMainSection_Sorting">
                                                                <Columns>
                                                                    <asp:TemplateField HeaderText="Section Name" SortExpression="section_name">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblSectionName" runat="server" Text='<%# Eval("section_name") %>' />
                                                                            <asp:TextBox ID="txtSectionName" runat="server" Text='<%# Eval("section_name") %>'
                                                                                Visible="false" Width="320px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Color">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblcssClassName" runat="server" CssClass="fc-DarkBlue" />
                                                                            <asp:DropDownList ID="ddlcssClassName" runat="server" Visible="false" OnSelectedIndexChanged="GetCssClassName" AutoPostBack="true">
                                                                                <asp:ListItem Text="RoyalBlue" Value="fc-RoyalBlue" class="fc-RoyalBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="CadetBlue" Value="fc-CadetBlue" class="fc-CadetBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="Blue" Value="fc-Blue" class="fc-Blue"></asp:ListItem>
                                                                                <asp:ListItem Text="Coral" Value="fc-Coral" class="fc-Coral"></asp:ListItem>
                                                                                <asp:ListItem Text="BlueViolet" Value="fc-BlueViolet" class="fc-BlueViolet"></asp:ListItem>
                                                                                <asp:ListItem Text="Brown" Value="fc-Brown" class="fc-Brown"></asp:ListItem>
                                                                                <asp:ListItem Text="Chartreuse" Value="fc-Chartreuse" class="fc-Chartreuse"></asp:ListItem>
                                                                                <asp:ListItem Text="CornflowerBlue" Value="fc-CornflowerBlue" class="fc-CornflowerBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="Crimson" Value="fc-Crimson" class="fc-Crimson"></asp:ListItem>
                                                                                <asp:ListItem Text="DarkOliveGreen" Value="fc-DarkOliveGreen" class="fc-DarkOliveGreen"></asp:ListItem>
                                                                                <asp:ListItem Text="MediumPurple" Value="fc-MediumPurple" class="fc-MediumPurple"></asp:ListItem>
                                                                                <asp:ListItem Text="Yellow" Value="fc-Yellow" class="fc-Yellow"></asp:ListItem>
                                                                                <asp:ListItem Text="GoldenRod" Value="fc-GoldenRod" class="fc-GoldenRod"></asp:ListItem>
                                                                                <asp:ListItem Text="Violet" Value="fc-Violet" class="fc-Violet"></asp:ListItem>
                                                                                <asp:ListItem Text="Tomato" Value="fc-Tomato" class="fc-Tomato"></asp:ListItem>
                                                                                <asp:ListItem Text="Indigo" Value="fc-Indigo" class="fc-Indigo"></asp:ListItem>
                                                                                <asp:ListItem Text="Teal" Value="fc-Teal" class="fc-Teal"></asp:ListItem>
                                                                                <asp:ListItem Text="Tan" Value="fc-Tan" class="fc-Tan"></asp:ListItem>
                                                                                <asp:ListItem Text="SteelBlue" Value="fc-SteelBlue" class="fc-SteelBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="SpringGreen" Value="fc-SpringGreen" class="fc-SpringGreen"></asp:ListItem>
                                                                                <asp:ListItem Text="SlateGrey" Value="fc-SlateGrey" class="fc-SlateGrey"></asp:ListItem>
                                                                                <asp:ListItem Text="SlateBlue" Value="fc-SlateBlue" class="fc-SlateBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="SkyBlue" Value="fc-SkyBlue" class="fc-SkyBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="SeaGreen" Value="fc-SeaGreen" class="fc-SeaGreen"></asp:ListItem>
                                                                                <asp:ListItem Text="SandyBrown" Value="fc-SandyBrown" class="fc-SandyBrown"></asp:ListItem>
                                                                                <asp:ListItem Text="IndianRed" Value="fc-IndianRed" class="fc-IndianRed"></asp:ListItem>
                                                                                <asp:ListItem Text="Aqua" Value="fc-Aqua" class="fc-Aqua"></asp:ListItem>
                                                                                <asp:ListItem Text="RosyBrown" Value="fc-RosyBrown" class="fc-RosyBrown"></asp:ListItem>
                                                                                <asp:ListItem Text="Red" Value="fc-Red" class="fc-Red"></asp:ListItem>
                                                                                <asp:ListItem Text="Purple" Value="fc-Purple" class="fc-Purple"></asp:ListItem>
                                                                                <asp:ListItem Text="YellowGreen" Value="fc-YellowGreen" class="fc-YellowGreen"></asp:ListItem>
                                                                                <asp:ListItem Text="RebeccaPurple" Value="fc-RebeccaPurple" class="fc-RebeccaPurple"></asp:ListItem>
                                                                                <asp:ListItem Text="DarkSlateGray" Value="fc-DarkSlateGray" class="fc-DarkSlateGray"></asp:ListItem>
                                                                                <asp:ListItem Text="DarkOrange" Value="fc-DarkOrange" class="fc-DarkOrange"></asp:ListItem>
                                                                                <asp:ListItem Text="PaleVioletRed" Value="fc-PaleVioletRed" class="fc-PaleVioletRed"></asp:ListItem>
                                                                                <asp:ListItem Text="OliveDrab" Value="fc-OliveDrab" class="fc-OliveDrab"></asp:ListItem>
                                                                                <asp:ListItem Text="DeepPink" Value="fc-DeepPink" class="fc-DeepPink"></asp:ListItem>
                                                                                <asp:ListItem Text="OrangeRed" Value="fc-OrangeRed" class="fc-OrangeRed"></asp:ListItem>
                                                                                <asp:ListItem Text="Orange" Value="fc-Orange" class="fc-Orange"></asp:ListItem>
                                                                                <asp:ListItem Text="Navy" Value="fc-Navy" class="fc-Navy"></asp:ListItem>
                                                                                <asp:ListItem Text="DimGrey" Value="fc-DimGrey" class="fc-DimGrey"></asp:ListItem>
                                                                                <asp:ListItem Text="MediumVioletRed" Value="fc-MediumVioletRed" class="fc-MediumVioletRed"></asp:ListItem>
                                                                                <asp:ListItem Text="Magenta" Value="fc-Magenta" class="fc-Magenta"></asp:ListItem>
                                                                                <asp:ListItem Text="MidnightBlue" Value="fc-MidnightBlue" class="fc-MidnightBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="Green" Value="fc-Green" class="fc-Green"></asp:ListItem>
                                                                                <asp:ListItem Text="MediumSlateBlue" Value="fc-MediumSlateBlue" class="fc-MediumSlateBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="MediumOrchid" Value="fc-MediumOrchid" class="fc-MediumOrchid"></asp:ListItem>
                                                                                <asp:ListItem Text="LimeGreen" Value="fc-LimeGreen" class="fc-LimeGreen"></asp:ListItem>
                                                                                <asp:ListItem Text="Salmon" Value="fc-Salmon" class="fc-Salmon"></asp:ListItem>
                                                                                <asp:ListItem Text="DarkSlateBlue" Value="fc-DarkSlateBlue" class="fc-DarkSlateBlue"></asp:ListItem>
                                                                                <asp:ListItem Text="DarkBlue" Value="fc-DarkBlue" class="fc-DarkBlue"></asp:ListItem>
                                                                            </asp:DropDownList>
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="12%" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Active">
                                                                        <ItemTemplate>
                                                                            <asp:CheckBox ID="chkIsActive" runat="server" Checked='<%# Eval("is_active") %>' />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="7%" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Ex. Comm.">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblAExcludeCom0" runat="server" />
                                                                            <asp:CheckBox ID="chkIsExcludeCom0" runat="server" Checked='<%# Eval("is_CommissionExclude") %>' Visible="false" />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="9%" />
                                                                    </asp:TemplateField>
                                                                    <asp:ButtonField CommandName="Edit" Text="Edit" />

                                                                </Columns>
                                                                <AlternatingRowStyle CssClass="alt" />
                                                            </asp:GridView>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" colspan="2" valign="top">
                                                <asp:Label ID="lblTree" runat="server">Tree Navigation:</asp:Label>
                                                <asp:Label ID="lblParent" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2" valign="top">
                                                <table width="100%" class="subHeader01">
                                                    <tr>
                                                        <td>
                                                            <asp:Label ID="lblSubSection" runat="server" Text="Sub Section" Visible="false"></asp:Label>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="background-color: #eaeff9;" align="center" colspan="2">
                                                <table>
                                                    <tr>
                                                        <td align="center">
                                                            <asp:Label ID="lblSubSecResult" runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="right">
                                                             <asp:Button ID="btnUpdateSerial" runat="server" CssClass="button" OnClick="btnUpdateSerial_Click" Text="Update Serial" Visible="true" />
                                                            &nbsp;
                                                            <asp:Button ID="btnAddSubnewRow" runat="server" CssClass="button" OnClick="btnAddSubnewRow_Click" Text="Add New Sub Section" Visible="False" />
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <asp:GridView ID="grdSubSection" runat="server" AutoGenerateColumns="False" CssClass="mGrid"
                                                                OnRowCommand="grdSubSection_RowCommand" OnRowDataBound="grdSubSection_RowDataBound"
                                                                OnRowEditing="grdSubSection_RowEditing" OnRowUpdating="grdSubSection_RowUpdating"
                                                                PageSize="200" TabIndex="2" Width="500px" AllowSorting="True" OnSorting="grdSubSection_Sorting">
                                                                <Columns>
                                                                    <asp:TemplateField HeaderText="Sub Section Name" SortExpression="section_name">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblSubSectionName" runat="server" Text='<%# Eval("section_name") %>' />
                                                                            <asp:TextBox ID="txtSubSectionName" runat="server" Text='<%# Eval("section_name") %>'
                                                                                Visible="false" Width="320px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Active">
                                                                        <ItemTemplate>
                                                                            <asp:CheckBox ID="chkIsActive1" runat="server" Checked='<%# Eval("is_active") %>' />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="8%" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Ex. Comm.">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblAExcludeCom1" runat="server" />
                                                                            <asp:CheckBox ID="chkIsExcludeCom1" runat="server" Checked='<%# Eval("is_CommissionExclude") %>' Visible="false" />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="15%" />
                                                                    </asp:TemplateField>
                                                                    <asp:ButtonField CommandName="Edit" Text="Edit" />
                                                                    <asp:TemplateField HeaderText="Serial">
                                                                        <ItemStyle HorizontalAlign="Center" Width="5%"></ItemStyle>
                                                                        <ItemTemplate>
                                                                            <asp:TextBox ID="txtItemSerial" Style="text-align: center;" CssClass="textBox" runat="server"  Width="30px"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <HeaderStyle HorizontalAlign="Center"></HeaderStyle>
                                                                    </asp:TemplateField>
                                                                </Columns>
                                                                <AlternatingRowStyle CssClass="alt" />
                                                            </asp:GridView>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2" valign="top">&nbsp;
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2" valign="top">
                                                <table width="100%" class="subHeader02">
                                                    <tr>
                                                        <td>
                                                            <asp:Label ID="lblItemList" runat="server" Text="Item List" Visible="false"></asp:Label>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="background-color: #bcc6dd;" align="center" colspan="2">
                                                <table width="100%">
                                                    <tr>
                                                        <td align="center">
                                                            <asp:Label ID="lblItemResult" runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="right">
                                                            <asp:Button ID="btnUpdateItemSerial" runat="server" CssClass="button" OnClick="btnUpdateItemSerial_Click" Text="Update Item Serial" Visible="true" />
                                                             <asp:TextBox ID="txtItemList" runat="server" TextMode="MultiLine" Height="50px" Width="150px"></asp:TextBox>
                                                            <asp:TextBox ID="txtMainSectionName" runat="server"></asp:TextBox>                                                           
                                                            <asp:Button ID="btnDisable" runat="server" CssClass="button" OnClick="btnDisable_Click" Text="Disable Item" Visible="true" />
                                                            <asp:Button ID="btnAddItem" runat="server" CssClass="button" OnClick="btnAddItem_Click" Text="Add New Item" Visible="false" />
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <asp:GridView ID="grdItem_Price" runat="server" AutoGenerateColumns="False" CssClass="mGrid"
                                                                OnRowCommand="grdItem_Price_RowCommand" OnRowDataBound="grdItem_Price_RowDataBound"
                                                                OnRowEditing="grdItem_Price_RowEditing" OnRowUpdating="grdItem_Price_RowUpdating"
                                                                PageSize="200" TabIndex="2" Width="98%" AllowSorting="True" OnSorting="grdItem_Price_Sorting">
                                                                <Columns>
                                                                    <asp:TemplateField HeaderText="Item Name" SortExpression="section_name">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblItemnName" runat="server" Text='<%# Eval("section_name") %>' />
                                                                            <asp:TextBox ID="txtItemName" runat="server" Text='<%# Eval("section_name") %>' Visible="false"
                                                                                Width="320px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="UOM">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblMeasureUnit" runat="server" Text='<%# Eval("measure_unit") %>' />
                                                                            <asp:TextBox ID="txtMeasureUnit" runat="server" Text='<%# Eval("measure_unit") %>'
                                                                                Visible="false" Width="100px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Cost">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblCost" runat="server" Text='<%# Eval("item_cost") %>' />
                                                                            <asp:TextBox ID="txtCost" runat="server" Text='<%# Eval("item_cost") %>' Visible="false"
                                                                                Width="80px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Right" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Minimum Qty">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblMinQty" runat="server" Text='<%# Eval("minimum_qty") %>' />
                                                                            <asp:TextBox ID="txtMinQty" runat="server" Text='<%# Eval("minimum_qty") %>' Visible="false"
                                                                                Width="80px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Retail multiplier">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblRetailMulti" runat="server" Text='<%# Eval("retail_multiplier") %>' />
                                                                            <asp:TextBox ID="txtRetailMulti" runat="server" Text='<%# Eval("retail_multiplier") %>'
                                                                                Visible="false" Width="80px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Labor rate">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblLabor" runat="server" Text='<%# Eval("labor_rate") %>' />
                                                                            <asp:TextBox ID="txtLabor" runat="server" Text='<%# Eval("labor_rate") %>' Visible="false"
                                                                                Width="80px" Wrap="False"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                         <ItemStyle HorizontalAlign="Right" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Active">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblActive" runat="server" />
                                                                            <asp:CheckBox ID="chkIsActiveItem" runat="server" Checked='<%# Eval("is_active") %>' Visible="false" />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="7%" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Mandatory">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblAMandatory" runat="server" />
                                                                            <asp:CheckBox ID="chkIsMandatory" runat="server" Checked='<%# Eval("is_mandatory") %>' Visible="false" />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="9%" />
                                                                    </asp:TemplateField>
                                                                    <asp:TemplateField HeaderText="Ex. Comm.">
                                                                        <ItemTemplate>
                                                                            <asp:Label ID="lblAExcludeCom" runat="server" />
                                                                            <asp:CheckBox ID="chkIsExcludeCom" runat="server" Checked='<%# Eval("is_CommissionExclude") %>' Visible="false" />
                                                                        </ItemTemplate>
                                                                        <ItemStyle HorizontalAlign="Center" Width="9%" />
                                                                    </asp:TemplateField>
                                                                    <asp:ButtonField CommandName="Edit" Text="Edit" />

                                                                       <asp:TemplateField HeaderText="Disable" Visible="true">
                                                                        <ItemTemplate>
                                                                            <asp:CheckBox ID="chkIsDisable" runat="server" />
                                                                        </ItemTemplate>
                                                                    </asp:TemplateField>
                                                                    <asp:BoundField DataField="section_id" HeaderText="section_id" ReadOnly="true"/>
                                                                      <asp:TemplateField HeaderText="Serial">
                                                                        <ItemStyle HorizontalAlign="Center" Width="5%"></ItemStyle>
                                                                        <ItemTemplate>
                                                                            <asp:TextBox ID="txtItemSerial" Style="text-align: center;" CssClass="textBox" runat="server"  Width="30px"></asp:TextBox>
                                                                        </ItemTemplate>
                                                                        <HeaderStyle HorizontalAlign="Center"></HeaderStyle>
                                                                    </asp:TemplateField>
                                                                </Columns>
                                                                <AlternatingRowStyle CssClass="alt" />
                                                            </asp:GridView>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="right">&nbsp;<td align="left">&nbsp;
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="right" colspan="2">
                                            &nbsp;
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2">
                                                <asp:Label ID="lblResult" runat="server" Text=""></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2">&nbsp;&nbsp;<asp:Button ID="btnClose" runat="server" CssClass="redButton" Text="Close"
                                                TabIndex="4" OnClick="btnClose_Click" />
                                            </td>
                                        </tr>
                                    </table>
                                    <asp:HiddenField ID="hdnSectionLevel" runat="server" Value="0" />
                                    <asp:HiddenField ID="hdnParentId" runat="server" Value="0" />
                                    <asp:HiddenField ID="hdnItem" runat="server" Value="0" />
                                    <asp:HiddenField ID="hdnMultiplier" runat="server" Value="0" />
                                    &nbsp;<asp:HiddenField ID="hdnSectionId" runat="server" Value="0" />
                                    <asp:Label ID="lblSerial" runat="server" Visible="False"></asp:Label>
                                    <asp:HiddenField ID="hdnTrvSelectedValue" runat="server" Value="0" />
                                    &nbsp;<asp:HiddenField ID="hdnSectionSerial" runat="server" Value="0" />
                                    <asp:HiddenField ID="hdnSubItemParentId" runat="server" Value="0" />
                                    <asp:HiddenField ID="hdnOrder" runat="server" Value="ASC" />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </ContentTemplate>
    </asp:UpdatePanel>
    <asp:UpdateProgress ID="UpdateProgress1" runat="server" DisplayAfter="1" AssociatedUpdatePanelID="UpdatePanel1" DynamicLayout="False">
        <ProgressTemplate>
            <div class="overlay" />
            <div class="overlayContent">
                <p>
                    Please wait while your data is being processed
                </p>
                <img src="images/ajax_loader.gif" alt="Loading" border="1" />
            </div>
        </ProgressTemplate>
    </asp:UpdateProgress>
</asp:Content>

