#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="masterclientdb")]
public partial class MasterDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMasterClient(MasterClient instance);
  partial void UpdateMasterClient(MasterClient instance);
  partial void DeleteMasterClient(MasterClient instance);
  partial void InsertMasterUserInfo(MasterUserInfo instance);
  partial void UpdateMasterUserInfo(MasterUserInfo instance);
  partial void DeleteMasterUserInfo(MasterUserInfo instance);
  #endregion
	
	public MasterDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MasterDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MasterDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MasterDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MasterDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MasterDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<MasterClient> MasterClients
	{
		get
		{
			return this.GetTable<MasterClient>();
		}
	}
	
	public System.Data.Linq.Table<MasterUserInfo> MasterUserInfos
	{
		get
		{
			return this.GetTable<MasterUserInfo>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasterClient")]
public partial class MasterClient : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MasterClientId;
	
	private System.Nullable<int> _client_id;
	
	private string _client_url;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasterClientIdChanging(int value);
    partial void OnMasterClientIdChanged();
    partial void Onclient_idChanging(System.Nullable<int> value);
    partial void Onclient_idChanged();
    partial void Onclient_urlChanging(string value);
    partial void Onclient_urlChanged();
    #endregion
	
	public MasterClient()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterClientId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MasterClientId
	{
		get
		{
			return this._MasterClientId;
		}
		set
		{
			if ((this._MasterClientId != value))
			{
				this.OnMasterClientIdChanging(value);
				this.SendPropertyChanging();
				this._MasterClientId = value;
				this.SendPropertyChanged("MasterClientId");
				this.OnMasterClientIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="Int")]
	public System.Nullable<int> client_id
	{
		get
		{
			return this._client_id;
		}
		set
		{
			if ((this._client_id != value))
			{
				this.Onclient_idChanging(value);
				this.SendPropertyChanging();
				this._client_id = value;
				this.SendPropertyChanged("client_id");
				this.Onclient_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_url", DbType="NVarChar(100)")]
	public string client_url
	{
		get
		{
			return this._client_url;
		}
		set
		{
			if ((this._client_url != value))
			{
				this.Onclient_urlChanging(value);
				this.SendPropertyChanging();
				this._client_url = value;
				this.SendPropertyChanged("client_url");
				this.Onclient_urlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasterUserInfo")]
public partial class MasterUserInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MasterUserId;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<int> _client_id;
	
	private string _first_name;
	
	private string _last_name;
	
	private string _email;
	
	private string _phone;
	
	private string _password;
	
	private System.Nullable<bool> _is_active;
	
	private System.Nullable<int> _user_type;
	
	private System.Nullable<System.DateTime> _create_date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasterUserIdChanging(int value);
    partial void OnMasterUserIdChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onclient_idChanging(System.Nullable<int> value);
    partial void Onclient_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void Onuser_typeChanging(System.Nullable<int> value);
    partial void Onuser_typeChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    #endregion
	
	public MasterUserInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterUserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MasterUserId
	{
		get
		{
			return this._MasterUserId;
		}
		set
		{
			if ((this._MasterUserId != value))
			{
				this.OnMasterUserIdChanging(value);
				this.SendPropertyChanging();
				this._MasterUserId = value;
				this.SendPropertyChanged("MasterUserId");
				this.OnMasterUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="Int")]
	public System.Nullable<int> client_id
	{
		get
		{
			return this._client_id;
		}
		set
		{
			if ((this._client_id != value))
			{
				this.Onclient_idChanging(value);
				this.SendPropertyChanging();
				this._client_id = value;
				this.SendPropertyChanged("client_id");
				this.Onclient_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(50)")]
	public string first_name
	{
		get
		{
			return this._first_name;
		}
		set
		{
			if ((this._first_name != value))
			{
				this.Onfirst_nameChanging(value);
				this.SendPropertyChanging();
				this._first_name = value;
				this.SendPropertyChanged("first_name");
				this.Onfirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(50)")]
	public string last_name
	{
		get
		{
			return this._last_name;
		}
		set
		{
			if ((this._last_name != value))
			{
				this.Onlast_nameChanging(value);
				this.SendPropertyChanging();
				this._last_name = value;
				this.SendPropertyChanged("last_name");
				this.Onlast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
	public System.Nullable<bool> is_active
	{
		get
		{
			return this._is_active;
		}
		set
		{
			if ((this._is_active != value))
			{
				this.Onis_activeChanging(value);
				this.SendPropertyChanging();
				this._is_active = value;
				this.SendPropertyChanged("is_active");
				this.Onis_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="Int")]
	public System.Nullable<int> user_type
	{
		get
		{
			return this._user_type;
		}
		set
		{
			if ((this._user_type != value))
			{
				this.Onuser_typeChanging(value);
				this.SendPropertyChanging();
				this._user_type = value;
				this.SendPropertyChanged("user_type");
				this.Onuser_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> create_date
	{
		get
		{
			return this._create_date;
		}
		set
		{
			if ((this._create_date != value))
			{
				this.Oncreate_dateChanging(value);
				this.SendPropertyChanging();
				this._create_date = value;
				this.SendPropertyChanged("create_date");
				this.Oncreate_dateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
